

services:
  autotici:
    image: autotici_docker
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["conda", "run", "--no-capture-output", "-n", "autotici_env", "python", "autoTICI.py"]
    volumes:
      - ./input_images:/app/input_images
      - ./output:/app/output
      - ./models:/app/models
    working_dir: /app
    command:
      - "-v"
      - "ap"
      - "input_images/R3418/SN3_Vap_SOP1.2.826.0.1.3680043.9.6827.2401407280984092171337075126937802959.dcm"
      - "input_images/R3418/SN10_Vap_SOP1.2.826.0.1.3680043.9.6827.2619603212203373380215256193355264957.dcm"
      - "ICA"

  phase_predict:
    image: autotici_docker
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["conda", "run", "--no-capture-output", "-n", "autotici_env", "python", "phase_classification/phase_predict.py"]
    volumes:
      - ./input_images:/app/input_images
      - ./output:/app/output
      - ./models:/app/models
    command: ["input_images/R3418/SN3_Vap_SOP1.2.826.0.1.3680043.9.6827.2401407280984092171337075126937802959.dcm"]
